#!/bin/bash -eu

SCALE=10000
TRANSACTIONS=100000
CONCURRENCY=10

echo ">> Old Schema - INSERT <<"
dropdb --if-exists getsentry_pgbench
createdb -E utf-8 getsentry_pgbench
psql getsentry_pgbench < schema-current.sql > /dev/null
pgbench getsentry_pgbench -n -c $CONCURRENCY -t $TRANSACTIONS -s $SCALE -f test-current.sql

echo ">> New Schema - INSERT <<"
dropdb --if-exists getsentry_pgbench
createdb -E utf-8 getsentry_pgbench
psql getsentry_pgbench < schema-new.sql > /dev/null
pgbench getsentry_pgbench -n -c $CONCURRENCY -t $TRANSACTIONS -s $SCALE -f test-new.sql

# TODO(dcramer): UPDATE tests, gonna be hard, also concurrency is kind of a lie with
# with updates since buffers mostly eliminate concurrent writes to the same row
